name: example
description: An example of how to use the declarative animated list widget.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  built_collection: ^4.2.2
  equatable: ^0.2.6
  declarative_animated_list:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
