name: declarative_animated_list
description: An implementation of animated list widget that will be automatically updated based on different lists snippets.
version: 0.0.1
author: Andrii Iliunin
homepage: https://github.com/nyarian

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.0
